import React from "react"
import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <header className={styles.header}>
            </header>

            <main className={styles.main}>
                <Container fluid>
                    <Row>
                        <h1 className={styles.title}>
                            Michael D. Hegerhorst
                        </h1>
                        <p className={styles.description}>
                            Short description here.
                        </p>
                    </Row>
                    <Row>
                        <Col>
                            <h2>About Me</h2>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget ipsum leo.
                                Curabitur
                                vitae sollicitudin odio. Integer vel consectetur sem. Proin eget purus sem. Fusce
                                bibendum ligula accumsan condimentum porttitor. Quisque et fermentum massa. Etiam
                                viverra metus eget neque feugiat, vel consectetur tortor lobortis.
                            </p>
                        </Col>
                        <Col>
                            PORTFOLIO PICTURE HERE
                        </Col>
                        <Col>
                            <h2>Details</h2>
                            <h3>Education:</h3>
                            <p>Degree 1 from University of State 1</p>
                            <p>Degree 2 from University of State 2</p>
                            <h3>Contact:</h3>
                            <p>my.email@email.com</p>
                        </Col>
                    </Row>
                </Container>
            </main>
            <footer className={styles.footer}>
            </footer>
        </div>
    )
}

export default Home
